const StudentTransferData = require('../models/student-transfer-data.models');

module.exports = {
  UserController: require('./user.controller'),
  StudentController: require('./student.controller'),
  ProfessorController: require('./professor.controller'),
  PaymentController: require('./payment.controller'),
  CourseController: require('./course.controller'),
  LevelController: require('./level.controller'),
  AttendanceController: require('./attendance.controller'),
  HolidaysController: require('./holidays.controller'),
  CancelledLessonController: require('./cancelled-lesson.controller'),
  UserController: require('./user.controller'),
  StudentController: require('./student.controller'),
  ProfessorController: require('./professor.controller'),
  PaymentController: require('./payment.controller'),
  CourseController: require('./course.controller'),
  LevelController: require('./level.controller'),
  AttendanceController: require('./attendance.controller'),
  HolidaysController: require('./holidays.controller'),
  SyllabusController: require('./syllabus.controller'),
  CourseScheduleController: require('./course-schedule.controller'),
  CourseGradingController: require('./course-grading.controller'),
  StudentGradesController: require('./student-grades.controller'),
  RegisteredStudentController: require('./registered-student.controller'),
  StudentTransferDataController: require('./student-transfer-data.controller'),
};
