module.exports = {
  UserController: require('./user.controller'),
  StudentController: require('./student.controller'),
  ProfessorController: require('./professor.controller'),
  PaymentController: require('./payment.controller'),
  CourseController: require('./course.controller'),
  LevelController: require('./level.controller'),
  AttendanceController: require('./attendance.controller'),
  HolidaysController: require('./holidays.controller'),
  CancelledLessonController: require('./cancelled-lesson.controller'),
  SyllabusController: require('./syllabus.controller'),
  CourseScheduleController: require('./course-schedule.controller'),
  CourseGradingController: require('./course-grading.controller'),
  StudentGradesController: require('./student-grades.controller'),
  RegisteredStudentController: require('./registered-student.controller'),
  TransferDataController: require('./transfer-data.controller'),
  StudentTransferController: require('./student-transfer.controller'),
  PrivateClassHoursController: require('./private-class-hours.controller'),
  PermissionsController: require('./permissions.controller'),
};
