module.exports = {
  UserService: require('./user.service'),
  StudentService: require('./student.service'),
  ProfessorService: require('./professor.service'),
  PaymentService: require('./payment.service'),
  CourseService: require('./course.service'),
  LevelService: require('./level.service'),
  AttendanceService: require('./attendance.service'),
  HolidaysService: require('./holidays.service'),
  SyllabusService: require('./syllabus.service'),
  CancelledLessonService: require('./cancelled-lesson.service'),
  CourseScheduleService: require('./course-schedule.service'),
  CourseGradingService: require('./course-grading.service'),
  StudentGradesService: require('./student-grades.service'),
  RegisteredStudentService: require('./registered-student.service'),
  TransferDataService: require('./transfer-data.service'),
  StudentTransferService: require('./student-transfer.service'),
};
