module.exports = {
  User: require('./user.models'),
  Student: require('./student.models'),
  Professor: require('./professor.models'),
  Payment: require('./payment.models'),
  Course: require('./course.models'),
  CourseStudent: require('./course-student.model'),
  Attendance: require('./attendance'),
  Grades: require('./grades'),
  Association: require('./associations'),
  Holidays: require('./holidays'),
  Syllabus: require('./syllabus'),
  SyllabusItems: require('./syllabusItems'),
  GradePercentages: require('./grade-percentages'),
  CancelledLesson: require('./cancelled-lesson.models'),
  CourseSchedule: require('./course-schedule.model'),
};
