module.exports = {
  User: require('./user.models'),
  Student: require('./student.models'),
  Professor: require('./professor.models'),
  Payment: require('./payment.models'),
  Course: require('./course.models'),
  CourseStudent: require('./course-student.model'),
  Attendance: require('./attendance'),
  Grades: require('./grades'),
  Association: require('./associations'),
  Holidays: require('./holidays'),
  Syllabus: require('./syllabus'),
  SyllabusItems: require('./syllabusItems'),
  GradePercentages: require('./grade-percentages'),
  CancelledLesson: require('./cancelled-lesson.models'),
  CourseSchedule: require('./course-schedule.model'),
  CourseGrading: require('./course-grading.model'),
  GradingItem: require('./grading-item.model'),
  GradingCategory: require('./grading-category.model'),
  StudentGrades: require('./student-grades.model'),
  Percentages: require('./percentages.model'),
  RegisteredStudent: require('./registered-student.model'),
  Level: require('./level.models'),
  StudentTransfer: require('./student-transfer.models'),
  TransferData: require('./transfer_data.models'),
};
